[33mwarn[39m:    Overriding option with key: "objectiveManager" based on preset DynaMOSA
[33mwarn[39m:    Overriding option with key: "secondaryObjectives" based on preset DynaMOSA
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

[33mwarn[39m:    'analysis-include' config parameter is empty so we only use the target files for analysis
[33mwarn[39m:    Computed property found in FunctionExpression at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/benchmark/crashes/syntest-collected/express/express-97/express/lib/application.js:475:16:::486:3:::10555:10831
[33mwarn[39m:    Computed property found in FunctionExpression at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/benchmark/crashes/syntest-collected/express/express-97/express/lib/application.js:475:16:::486:3:::10555:10831
Unable to insert counter for node identifierDescription: VariableDeclaration
Unable to insert counter for node identifierDescription: VariableDeclaration
â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘ 4% | ETA: INFs | 4/100 | 0% | application.js
[33mwarn[39m:    'analysis-include' config parameter is empty so we only use the target files for analysis
[33mwarn[39m:    Computed property found in FunctionExpression at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/benchmark/crashes/syntest-collected/express/express-98/express/lib/application.js:475:16:::486:3:::10555:10831
[33mwarn[39m:    Computed property found in FunctionExpression at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/benchmark/crashes/syntest-collected/express/express-98/express/lib/application.js:475:16:::486:3:::10555:10831
Unable to insert counter for node identifierDescription: VariableDeclaration
Unable to insert counter for node identifierDescription: VariableDeclaration
/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/libraries/search-javascript/dist/lib/testcase/execution/TestExecutor.js:25
    throw reason;
    ^

Error: listen EACCES: permission denied ./middleware/query
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
    at Server.apply [as listen] (node:net:1964:5)
    at Object.listen (application.js:620:24)
    at call (tempTest.spec.js:17:57)
    at tryCatch (tempTest.spec.js:2:1)
    at Generator._invoke (tempTest.spec.js:2:1)
    at Generator.next (tempTest.spec.js:2:1)
    at asyncGeneratorStep (tempTest.spec.js:2:1)
    at _next (tempTest.spec.js:2:1)
    at tempTest.spec.js:2:1
    at new Promise (<anonymous>)
    at Context.<anonymous> (tempTest.spec.js:2:1)
    at callFn (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:666:10)
    at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:789:12
    at next (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:581:14)
    at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:591:7
    at next (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:474:14)
    at cbHookRun (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:539:7)
    at done (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:354:5)
    at next (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:498:10)
    at Immediate.<anonymous> (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:559:5)
    at processImmediate (node:internal/timers:476:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: './middleware/query',
  port: -1
}

Node.js v18.19.0
[33mwarn[39m:    Execution timeout reached killing process, timeout: 5000 times 1
/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/libraries/search-javascript/dist/lib/testcase/execution/TestExecutor.js:25
    throw reason;
    ^

Error: listen EACCES: permission denied 4?'@*Sm/89d@oVKHK'+Auwt8utH@SA$Y:#SmP<5zt&]AOpUZ7$.jo& 
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
    at Server.apply [as listen] (node:net:1964:5)
    at Object.disable [as listen] (application.js:620:24)
    at call (tempTest.spec.js:17:41)
    at tryCatch (tempTest.spec.js:2:1)
    at Generator._invoke (tempTest.spec.js:2:1)
    at Generator.next (tempTest.spec.js:2:1)
    at asyncGeneratorStep (tempTest.spec.js:2:1)
    at _next (tempTest.spec.js:2:1)
    at tempTest.spec.js:2:1
    at new Promise (<anonymous>)
    at Context.<anonymous> (tempTest.spec.js:2:1)
    at callFn (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:666:10)
    at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:789:12
    at next (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:581:14)
    at /local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:591:7
    at next (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:474:14)
    at cbHookRun (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:539:7)
    at done (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runnable.js:354:5)
    at next (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:498:10)
    at Immediate.<anonymous> (/local/tmp/oliverphil/4261736.1/syntest-crash-reproduction/node_modules/mocha/lib/runner.js:559:5)
    at processImmediate (node:internal/timers:476:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: "4?'@*Sm/89d@oVKHK'+Auwt8utH@SA$Y:#SmP<5zt&]AOpUZ7$.jo& ",
  port: -1
}

Node.js v18.19.0
[33mwarn[39m:    Execution timeout reached killing process, timeout: 5000 times 1
â–ˆâ–ˆâ–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘â–‘ 4% | ETA: INFs | 4/100 | 0% | application.js
