AssertionError: expected 'Found. Redirecting to http://example.com/?param=%3Cscript%3Ealert(%22hax%22);%3C/script%3E' to be 'Moved Temporarily. Redirecting to http://example.com/?param=%3Cscript%3Ealert(%22hax%22);%3C/script%3E'
    at Assertion.fail (node_modules/should/lib/assertion.js:112:17)
    at Assertion.prop.(anonymous function) (node_modules/should/lib/assertion.js:38:14)
    at Test.<anonymous> (test/res.redirect.js:157:25)
    at Test.assert (node_modules/supertest/lib/test.js:221:6)
    at Server.assert (node_modules/supertest/lib/test.js:132:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitCloseNT (net.js:1577:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)