TypeError: The "name" argument must be of type string. Received function field
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at ServerResponse.getHeader (node:_http_outgoing:719:3)
    at ServerResponse.get (express/lib/response.js:794:15)
    at ServerResponse.arrayElement3 [as append] (express/lib/response.js:727:47)
    at call (.syntest/tests/tempTest.spec.js:21:9)
    at tryCatch (.syntest/tests/tempTest.spec.js:2:1)
    at Generator._invoke (.syntest/tests/tempTest.spec.js:2:1)
    at Generator.next (.syntest/tests/tempTest.spec.js:2:1)
    at asyncGeneratorStep (.syntest/tests/tempTest.spec.js:2:1)
    at _next (.syntest/tests/tempTest.spec.js:2:1)
    at .syntest/tests/tempTest.spec.js:2:1
    at new Promise (<anonymous>)
    at Context.<anonymous> (.syntest/tests/tempTest.spec.js:2:1)
    at processImmediate (node:internal/timers:478:21)
